import React from 'react';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  Bell,
  BellOff,
  BookOpen,
  Bookmark,
  Briefcase,
  Calendar,
  CalendarCheck,
  Camera,
  ChevronRight,
  Check,
  Plus,
  CheckCircle,
  Clock3,
  Command,
  Compass,
  CornerUpRight,
  Copy,
  Crosshair,
  Download,
  Globe,
  Handshake,
  Heart,
  HeartPulse,
  Hexagon,
  Home,
  Image,
  Inbox,
  Map,
  MapPin,
  Medal,
  Monitor,
  MoreVertical,
  Lock,
  Navigation,
  Palette,
  School,
  Search,
  Send,
  Share2,
  Shield,
  ShieldCheck,
  ShieldOff,
  Star,
  Stethoscope,
  Trash2,
  Trophy,
  User,
  Users,
  X,
  XCircle,
} from 'lucide-react-native';

type IconProps = {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: any;
};

const ICONS: Record<string, React.ComponentType<any>> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  bell: Bell,
  'bell-off': BellOff,
  'book-open': BookOpen,
  bookmark: Bookmark,
  briefcase: Briefcase,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  camera: Camera,
  'chevron-right': ChevronRight,
  check: Check,
  'check-circle': CheckCircle,
  clock: Clock3,
  command: Command,
  compass: Compass,
  'corner-right-up': CornerUpRight,
  copy: Copy,
  crosshair: Crosshair,
  download: Download,
  globe: Globe,
  handshake: Handshake,
  heart: Heart,
  'heart-pulse': HeartPulse,
  hexagon: Hexagon,
  home: Home,
  image: Image,
  inbox: Inbox,
  map: Map,
  'map-pin': MapPin,
  medal: Medal,
  monitor: Monitor,
  'more-vertical': MoreVertical,
  lock: Lock,
  navigation: Navigation,
  palette: Palette,
  plus: Plus,
  school: School,
  search: Search,
  send: Send,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-off': ShieldOff,
  star: Star,
  stethoscope: Stethoscope,
  'trash-2': Trash2,
  trophy: Trophy,
  user: User,
  users: Users,
  x: X,
  'x-circle': XCircle,
};

export default function AppIcon({
  name,
  size = 16,
  color = '#111827',
  strokeWidth = 2,
  style,
}: IconProps) {
  const LucideIcon = ICONS[name] ?? AlertCircle;

  return <LucideIcon size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}
